<?xml version="1.0"?>

<robot name="sam_bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define robot constants -->

  <xacro:property name="base_width" value="0.44"/>
  <xacro:property name="base_length" value="0.34"/>
  <xacro:property name="base_height" value="0.32"/>

  <xacro:property name="wheel_radius" value="0.08"/>
  <xacro:property name="wheel_width" value="0.03"/>
  <xacro:property name="wheel_ygap" value="0.075"/>
  <xacro:property name="wheel_zoff" value="0.23"/>
  <xacro:property name="wheel_xoff" value="0.29"/>

  <xacro:property name="caster_xoff" value="0.13"/>

  <!-- Define some commonly used intertial properties  -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>      
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />      
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/> 
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>
  
  <!-- Robot Base -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 0"/>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 0"/>
    </collision>

    <xacro:box_inertia m="1" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  
   <!-- Robot Footprint -->
  <link name="base_footprint">
  	<xacro:box_inertia m="0" w="0" d="0" h="0"/>
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/> 
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="1.5" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2-wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="left_wheel" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="right_wheel" x_reflect="-1" y_reflect="-1" />

    <!-- caster -->
    <!-- <xacro:macro name="caster" params="prefix x_reflect y_reflect">
      <link name="${prefix}_link">
        <visual>
          <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
          <geometry>
              <cylinder radius="${(wheel_radius+wheel_zoff-(base_height/2))}" length="${wheel_width}"/>
          </geometry>
          <material name="Gray">
            <color rgba="0.5 0.5 0.5 1.0"/>
          </material>
        </visual>
  
        <collision>
          <origin xyz="0 0 0" rpy="${pi/2} 0 0"/> 
          <geometry>
            <cylinder radius="${(wheel_radius+wheel_zoff-(base_height/2))}" length="${wheel_width}"/>
          </geometry>
        </collision>
  
        <xacro:cylinder_inertia m="0.5" r="${(wheel_radius+wheel_zoff-(base_height/2))}" h="${wheel_width}"/>
      </link>
  
      <joint name="${prefix}_joint" type="continuous">
        <parent link="base_link"/>
        <child link="${prefix}_link"/>
        <origin xyz="${x_reflect*caster_xoff} ${y_reflect*(base_width/2-wheel_ygap)} ${-(base_height/2)}" rpy="0 0 0"/>
        <axis xyz="1 1 1"/>
      </joint>
    </xacro:macro>
  
    <xacro:caster prefix="left_caster" x_reflect="1" y_reflect="1" />
    <xacro:caster prefix="right_caster" x_reflect="1" y_reflect="-1" /> -->
  

    <link name="left_front_caster">
      <visual>
        <geometry>
          <sphere radius="${(wheel_radius + wheel_zoff - (base_height / 2))}"/>
        </geometry>
        <material name="Cyan">
          <color rgba="0 1.0 1.0 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${(wheel_radius + wheel_zoff - (base_height / 2))}"/>
        </geometry>
      </collision>

      <xacro:sphere_inertia m="0.5" r="${(wheel_radius + wheel_zoff - (base_height / 2))}"/>
    </link>

    <!-- 右前万向轮 -->
    <link name="right_front_caster">
      <visual>
        <geometry>
          <sphere radius="${(wheel_radius + wheel_zoff - (base_height / 2))}"/>
        </geometry>
        <material name="Cyan">
          <color rgba="0 1.0 1.0 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${(wheel_radius + wheel_zoff - (base_height / 2))}"/>
        </geometry>
      </collision>

      <xacro:sphere_inertia m="0.5" r="${(wheel_radius + wheel_zoff - (base_height / 2))}"/>
    </link>

    <!-- 前万向轮关节 -->
    <joint name="left_front_caster_joint" type="fixed">
      <parent link="base_link"/>
      <child link="left_front_caster"/>
      <origin xyz="${caster_xoff} ${base_width / 2 - wheel_ygap} ${-(base_height / 2)}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>  <!-- 旋转轴 -->
    </joint>

    <joint name="right_front_caster_joint" type="fixed">
      <parent link="base_link"/>
      <child link="right_front_caster"/>
      <origin xyz="${caster_xoff} ${-(base_width / 2 - wheel_ygap)} ${-(base_height / 2)}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>  <!-- 旋转轴 -->
    </joint>

  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
    </visual>
    
    <collision>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
    </collision>
      
    <xacro:box_inertia m="0.05" w="0.05" d="0.05" h="0.02"/>
  </link>
     
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0.17" rpy="0 0 0"/>
  </joint>

  <gazebo reference="imu_link">
  <sensor name="imu_sensor" type="imu">
   <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
      <ros>
        <namespace>/demo</namespace>
        <remapping>~/out:=imu</remapping>
      </ros>
      <initial_orientation_as_reference>false</initial_orientation_as_reference>
    </plugin>
    <always_on>true</always_on>
    <update_rate>100</update_rate>
    <visualize>true</visualize>
    <imu>
      <angular_velocity>
        <x>
          <noise type="gaussian">
            <mean>0.0</mean>      <bias_stddev>0.001</bias_stddev>
            <stddev>2e-4</stddev>
            <bias_mean>0.0000075</bias_mean>
            <bias_stddev>0.0000008</bias_stddev>
          </noise>
        </x>
        <y>
          <noise type="gaussian">
            <mean>0.0</mean>
            <stddev>2e-4</stddev>
            <bias_mean>0.0000075</bias_mean>
            <bias_stddev>0.0000008</bias_stddev>
          </noise>
        </y>
        <z>
          <noise type="gaussian">
            <mean>0.0</mean>
            <stddev>2e-4</stddev>
            <bias_mean>0.0000075</bias_mean>
            <bias_stddev>0.0000008</bias_stddev>
          </noise>
        </z>
      </angular_velocity>
      <linear_acceleration>
        <x>
          <noise type="gaussian">
            <mean>0.0</mean>
            <stddev>1.7e-2</stddev>
            <bias_mean>0.1</bias_mean>
            <bias_stddev>0.001</bias_stddev>
          </noise>
        </x>
        <y>
          <noise type="gaussian">
            <mean>0.0</mean>
            <stddev>1.7e-2</stddev>
            <bias_mean>0.1</bias_mean>
            <bias_stddev>0.001</bias_stddev>
          </noise>
        </y>
        <z>
          <noise type="gaussian">
            <mean>0.0</mean>
            <stddev>1.7e-2</stddev>
            <bias_mean>0.1</bias_mean>
          </noise>
        </z>
      </linear_acceleration>
    </imu>
  </sensor>
</gazebo>
  
 <link name="lidar_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.125"/>
      <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
         <cylinder radius="0.06" length="0.09"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
         <cylinder radius="0.06" length="0.09"/>
      </geometry>
    </visual>
  </link>

    
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 0.285" rpy="0 0 0"/>
  </joint>


  <gazebo reference="lidar_link">
    <sensor name="lidar" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>5</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1.000000</resolution>
            <min_angle>0.000000</min_angle>
            <max_angle>6.280000</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.120000</min>
          <max>3.5</max>
          <resolution>0.015000</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>lidar_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Camera Front -->
  <link name="CAM_FRONT">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>
  <joint name="CAM_FRONT_joint" type="fixed">
    <parent link="base_link"/>
    <child link="CAM_FRONT"/>
    <origin xyz="0.17 0.0 0.185" rpy="0 0 0"/> <!-- 0° -->
  </joint>

  <!-- Camera Front Right -->
  <link name="CAM_FRONT_LEFT">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>
  <joint name="CAM_FRONT_LEFT_joint" type="fixed">
    <parent link="base_link"/>
    <child link="CAM_FRONT_LEFT"/>
    <origin xyz="0.12 0.22 0.185" rpy="0 0 1.0472"/> <!-- 60° -->
  </joint>

  <!-- Camera Back Right -->
  <link name="CAM_BACK_LEFT">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>
  <joint name="CAM_BACK_LEFT_joint" type="fixed">
    <parent link="base_link"/>
    <child link="CAM_BACK_LEFT"/>
    <origin xyz="-0.12 0.22 0.185" rpy="0 0 2.0944"/> <!-- 120° -->
  </joint>

  <!-- Camera Back -->
  <link name="CAM_BACK">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>
  <joint name="CAM_BACK_joint" type="fixed">
    <parent link="base_link"/>
    <child link="CAM_BACK"/>
    <origin xyz="-0.17 0.0 0.185" rpy="0 0 3.1416"/> <!-- 180° -->
  </joint>

  <!-- Camera Back Left -->
  <link name="CAM_BACK_RIGHT">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>
  <joint name="CAM_BACK_RIGHT_joint" type="fixed">
    <parent link="base_link"/>
    <child link="CAM_BACK_RIGHT"/>
    <origin xyz="-0.12 -0.22 0.185" rpy="0 0 -2.0944"/> <!-- 240° -->
  </joint>

  <!-- Camera Front Left -->
  <link name="CAM_FRONT_RIGHT">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>
  <joint name="CAM_FRONT_RIGHT_joint" type="fixed">
    <parent link="base_link"/>
    <child link="CAM_FRONT_RIGHT"/>
    <origin xyz="0.12 -0.22 0.185" rpy="0 0 -1.0472"/> <!-- 300° -->
  </joint>

</robot>
