controller_manager:
  ros__parameters:
    update_rate: 60  # Hz，控制器的更新频率

    # 状态广播器
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # 差速驱动控制器
    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

diffbot_base_controller:
  ros__parameters:
    # 关节名称，必须与 URDF 中的名称匹配
    left_wheel_names: ["left_wheel"]
    right_wheel_names: ["right_wheel"]

    # 机器人参数
    wheel_separation: 0.29  # 左右轮间距（单位：米）
    wheel_radius: 0.08      # 轮子半径（单位：米）

    # 校准参数
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # 发布频率
    publish_rate: 50.0  # 发布 /odom 和 /tf 话题的频率

    # 控制器配置
    use_stamped_vel: false  # 是否使用时间戳的速度命令
    odom_frame_id: odom     # 里程计坐标系
    base_frame_id: base_link # 机器人底盘坐标系
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]  # 位姿协方差
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01] # 速度协方差

    open_loop: false  # 是否启用开环模式
    enable_odom_tf: true  # 是否发布 /tf 变换

    cmd_vel_timeout: 0.5  # 在此时间内未收到速度指令则停止机器人

    # 速度和加速度限制
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 0.6
    linear.x.min_velocity: -0.6
    linear.x.max_acceleration: 1.0
    linear.x.min_acceleration: -1.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.8
    angular.z.min_acceleration: -1.8
