usb_camera_node:
  ros__parameters:
    frame_rate: 60
    image_width: 1920
    image_height: 1080
    img_type: PNG
    post_processing_img_width: 1600
    post_processing_img_height: 900
    flip_x: false  # Flip the image along the X-axis
    flip_y: false # Flip the image along the Y-axis
    is_img_show: false
